# ================================
# Build Stage
# ================================
FROM golang:latest AS builder

# Get GRPC packages
RUN go get -u -v google.golang.org/grpc
RUN go get -u -v github.com/golang/protobuf/protoc-gen-go

